package edu.pitt.cs;

import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import java.time.Duration;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void tEST2RESET() {
    driver.get("https://localhost:8080//reset");
    js.executeScript("document.cookie = \'1=true\'; document.cookie = \'2=true\'; document.cookie = \'3=true\';");
    driver.findElement(By.xpath("//a[text()=\'Reset\']")).click();
    {
      List<WebElement> elements = driver
          .findElements(By.xpath("//ul[@class=\'list-group\']/li[3][text()=\'ID 3. Mistoffelees\']"));
      assert (elements.size() > 0);
    }
  }

  // @Test
  // public void dEFECT1FUNRENT() {
  // driver.get("https://localhost:8080//rent-a-cat");
  // driver.findElement(By.id("rentID")).sendKeys("999");
  // driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
  // {
  // List<WebElement> elements =
  // driver.findElements(By.xpath("//dic[contains(@class, \'alert-danger\')]"));
  // assert (elements.size() > 0);
  // }
  // }

  // @Test
  // public void dEFECT2FUNFEED() {
  // driver.get("https://localhost:8080/");
  // driver.findElement(By.xpath("//a[text()=\'Feed-A-Cat\']")).click();
  // driver.findElement(By.id("catnips")).sendKeys("-3");
  // driver.findElement(By.xpath("//button[contains(text(),\'Feed\')]")).click();
  // assertThat(driver.findElement(By.id("feedResult")).getText(), is("Cat
  // fight!"));
  // }

  // @Test
  // public void dEFECT3FUNFUNGREETACAT() {
  // driver.get("https://localhost:8080//");
  // js.executeScript("document.cookie = \'1=true\'; document.cookie = \'2=true\';
  // document.cookie = \'3=true\';");
  // driver.findElement(By.xpath("//a[text()=\'Greet-A-Cat\']")).click();
  // {
  // List<WebElement> elements =
  // driver.findElements(By.xpath("//h4[contains(text(),\'Meow!Meow!Meow!\')]"));
  // assert (elements.size() == 0);
  // }
  // }

  @Test
  public void tEST1LINKS() {
    driver.get("https://localhost:8080//");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(text(),\'Reset\')]"));
      assert (elements.size() > 0);
    }
    {
      WebElement element = driver.findElement(By.linkText("Reset"));
      String attribute = element.getAttribute("href");
      vars.put("linkHref", attribute);
    }
    assertEquals(vars.get("linkHref").toString(), "https://localhost:8080/reset");
  }

  @Test
  public void tEST3CATALOG() {
    driver.get("https://localhost:8080//");
    driver.findElement(By.xpath("//a[text()=\'Catalog\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//ol/li[2]/img")));
    }
    {
      WebElement element = driver.findElement(By.xpath("//ol/li[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("linkHref", attribute);
    }
    assertEquals(vars.get("linkHref").toString(), "https://localhost:8080/images/cat2.jpg");
  }

  @Test
  public void tEST6RENT() {
    driver.get("https://localhost:8080//reset");
    driver.findElement(By.xpath("//a[text()=\'Rent-A-Cat\']")).click();
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.xpath("//button[contains(text(),\'Rent\')]")).click();
    {
      List<WebElement> elements = driver
          .findElements(By.xpath("//ul[@class=\'list-group\']/li[1][text()=\'Rented out\']"));
      assert (elements.size() > 0);
    }
    {
      List<WebElement> elements = driver
          .findElements(By.xpath("//ul[@class=\'list-group\']/li[2][text()=\'ID 2. Old Deuteronomy\']"));
      assert (elements.size() > 0);
    }
    {
      List<WebElement> elements = driver
          .findElements(By.xpath("//ul[@class=\'list-group\']/li[3][text()=\'ID 3. Mistoffelees\']"));
      assert (elements.size() > 0);
    }
    assertThat(driver.findElement(By.id("rentResult")).getText(), is("Success!"));
  }

  @Test
  public void tEST5RENTACAT() {
    driver.get("https://localhost:8080//reset");
    driver.findElement(By.xpath("//a[text()=\'Rent-A-Cat\']")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Rent\']"));
      assert (elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Return\']	"));
      assert (elements.size() > 0);
    }
  }

  @Test
  public void tEST4LISTING() {
    driver.get("https://localhost:8080//reset");
    driver.findElement(By.xpath("//a[text()=\'Catalog\']")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("(//ul[contains(@class, \'list-group\')]//li[3])"));
      assert (elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("(//ul[contains(@class, \'list-group\')]//li[3])")).getText(),
        is("ID 3. Mistoffelees"));
  }

  @Test
  public void tEST7RETURN() {
    driver.get("https://localhost:8080//");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie == \"3=false\";");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie == \"3=false\";");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("returnID")).click();
    driver.findElement(By.id("returnID")).sendKeys("2");
    driver.findElement(By.xpath("//button[contains(text(),\'Return\')]")).click();
    assertThat(driver.findElement(By.id("cat-id1")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.xpath("//li[contains(.,\'ID 2. Old Deuteronomy\')]")).getText(),
        is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//li[contains(.,\'ID 3. Mistoffelees\')]")).getText(),
        is("ID 3. Mistoffelees"));
    assertThat(driver.findElement(By.xpath("//div[@id=\'returnResult\']")).getText(), is("Success!"));
  }

  @Test
  public void tEST8FEEDACAT() {
    driver.get("https://localhost:8080//reset");
    driver.findElement(By.xpath("//a[text()=\'Feed-A-Cat\']")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(text(),\'Feed\')]"));
      assert (elements.size() > 0);
    }
  }

  @Test
  public void tEST9FEED() {
    driver.get("https://localhost:8080//reset");
    driver.findElement(By.xpath("//a[text()=\'Feed-A-Cat\']")).click();
    driver.findElement(By.id("catnips")).sendKeys("6");
    driver.findElement(By.xpath("//button[contains(text(),\'Feed\')]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.id("feedResult"), "Nom, nom, nom."));
    }
    assertThat(driver.findElement(By.id("feedResult")).getText(), is("Nom, nom, nom."));
  }

  @Test
  public void tEST10GREETACAT() {
    driver.get("https://localhost:8080//reset");
    driver.findElement(By.xpath("//a[text()=\'Greet-A-Cat\']")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(text(),\'Meow!Meow!Meow!\')]"));
      assert (elements.size() > 0);
    }
  }

  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("https://localhost:8080/greet-a-cat/Jennyanydots	");
    assertThat(driver.findElement(By.xpath("//*[contains(text(), \'Meow! from Jennyanydots\')]")).getText(),
        is("Meow! from Jennyanydots."));
  }
}
